/*
 * generated by Xtext 2.27.0
 */
package fr.inria.sed.gpfl.xtext.validation

import org.eclipse.xtext.validation.Check
import fr.inria.sed.gpfl.GpflPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GpflValidator extends AbstractGpflValidator {

//	public static val MISSING_AUTOMATA = 'missingAutomata'
//
//	@Check
//	def checkAutomataDoesNotExist(Cmd cmd) {
//		if(cmd.automatonIdStep !== null
//			// && automatonIdStep is not in autmata list
//		) {
//			error('This automaton does not exist',
//				GpflPackage.Literals.CMD__AUTOMATON_ID_STEP,
//				MISSING_AUTOMATA
//			)
//		}
//	}

//	public static val MISSING_FIELD = 'missingvariable'
//
//	@Check
//	def checkFieldIdDoesNotExist(FieldIdConstant fieldIdConstant) {
//		if(fieldIdConstant.value !== null
//			// && value is not in field list for this package
//		) {
//			error('This field id does not exist',
//				GpflPackage.Literals.FIELD_ID_CONSTANT__VALUE,
//				MISSING_FIELD
//			)
//		}
//	}
}
