/*
 * generated by Xtext 2.27.0
 */
package fr.inria.diverse.gpfl.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GpflUiModule extends AbstractGpflUiModule {
}
